### PR TITLE
Added googletests

### PR DESCRIPTION
**Pull request by 0leksandrBondar**
I added the Google Test library to test the Messenger's codebase. I didn't add it as a submodule to ensure the security of our codebase.

If something breaks in the Google Test library, ours will still function properly. If an update is needed, we can simply replace the Google Test codebase

### CODE REVIEW

**Comment by 0leksandrBondar** [comment]
@Serhii-Nesteruk @ValeriiKoniushenko  review it please

**Comment by ValeriiKoniushenko** [comment]
Set reviewers into the special tab
And don't forget to assign a PR

**Comment by ValeriiKoniushenko** [comment]
It makes no sense to store GTests(or other submodules) like source code.
Just fetch it using cmake(with binding to X version)

**Comment by 0leksandrBondar** [comment]
> It makes no sense to store GTests(or other submodules) like source code. Just fetch it using cmake(with binding to X version)

what do you mean: Just fetch it using cmake

**Comment by ValeriiKoniushenko** [comment]
> > It makes no sense to store GTests(or other submodules) like source code. Just fetch it using cmake(with binding to X version)
> 
> @ValeriiKoniushenko what do you mean: Just fetch it using cmake

See above

**Review by ValeriiKoniushenko — APPROVED** [review]

**Pull request merged**
